stages:
  - build
  - test
  - deploy

image: alexsuch/angular-cli

deploy to production:
  stage: deploy
  environment: production
  when: manual
  script:
    - 'cp -r dist /tmp'
  only:
  - master

build:
  stage: build
  environment: staging
  script:
    - 'npm install'
    - 'ng build --prod'
