stages:
  - build
  - test
  - deploy

image: alexsuch/angular-cli

build:
  stage: build
  environment: staging
  artifacts:
    name: cm-website
    expire_in: 12 hrs
    paths:
    - dist/
  script:
    - 'npm install'
    - 'ng build --prod'

deploy to production:
  stage: deploy
  environment: production
  when: manual
  script:
    - 'cp -r dist /tmp'
  only:
  - master
